services:
  unknown-go-client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT:-7342}
      - XRAY_CONFIG_PATH=${XRAY_CONFIG_PATH:-/usr/local/etc/xray/config.json}
    volumes:
      - ${XRAY_CONFIG_PATH:-./config.json}:/usr/local/etc/xray/config.json